DROP TABLE IF EXISTS Widgets;

CREATE TABLE Widgets (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  x INT NOT NULL,
  y INT NOT NULL,
  width INT NOT NULL,
  height INT NOT NULL,
  zIndex INT AUTO_INCREMENT NOT NULL
);